[package]
name = "elokore/voxel-terrain"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[place]
shared-packages = "game:GetService('ReplicatedStorage').Packages"

[dependencies]
Janitor = "howmanysmall/janitor@^1.15.6"
Promise = "evaera/promise@^4.0.0"
Signal = "stravant/goodsignal@^0.2.1"
TableUtil = "sleitnick/table-util@1.2.0"

[server-dependencies]
Cmdr = "evaera/cmdr@^1.12.0"
ProfileStore = "lm-loleris/profilestore@1.0.2"
